from config import DEFAULT_LOCALE
from utils.locale_helper import get_admin_language


def get_admin_help_text() -> str:
    """
    Detailed admin help text.
    Language is selected based on admin locale (or DEFAULT_LOCALE).
    """
    lang = get_admin_language() or DEFAULT_LOCALE

    if lang == "en":
        return (
            "❓ Admin help\n\n"
            "📥 Inbox\n"
            "– List of all active tickets with short previews.\n"
            "– Each item shows: ticket ID, user, status and whose turn it is (👤 user / 🛠 support).\n"
            "– Tickets where it's support's turn (user replied last) are shown above others.\n"
            "– Inside each group tickets are sorted by creation time: newer above older.\n\n"
            "📄 Ticket card\n"
            "– Full view of a ticket: ID, user, status (New / In progress / Closed), creation time and full message history.\n"
            "– Turn indicator shows whose reply is expected now; if it's support's turn, the ticket is prioritized in the inbox.\n\n"
            "▶️ Take in work\n"
            "– Available only for tickets with status \"New\".\n"
            "– Switches status to \"In progress\" and marks that you started working on this ticket.\n"
            "– Use to make it clear for other admins that this ticket is already being handled.\n\n"
            "💬 Reply to user\n"
            "– Sends your message to the user with the ticket ID so the context is preserved.\n"
            "– After your reply, the turn moves to the user and the auto-close timer starts.\n"
            "– You can reply multiple times; the ticket stays open until you close it or auto-close is triggered.\n\n"
            "🔒 Close ticket\n"
            "– Manually closes the ticket (status \"Closed\").\n"
            "– Use when the issue is resolved or the ticket is no longer relevant.\n"
            "– The user receives a closure notification and, if rating is enabled, a request to rate support.\n\n"
            "⏰ Auto-close\n"
            "– Works only if support replied last and the user is silent for more than X hours.\n"
            "– X is configured via AUTO_CLOSE_AFTER_HOURS.\n"
            "– When the condition is met, the ticket is closed automatically with status \"Closed\".\n"
            "– Admin and user receive notifications about auto-close; the user also gets an \"Ask a question\" button to open a new ticket.\n\n"
            "📊 Statistics\n"
            "– Shows total users, total tickets, active and closed tickets.\n"
            "– Separately shows tickets waiting for auto-close (user's turn + timer running).\n"
            "– Includes rating block: number of rated tickets and average rating, plus short dynamics for the last days.\n\n"
            "💾 Backups\n"
            "– Automatic backups are created by the scheduler according to settings.\n"
            "– Manual backup can be triggered from the admin settings.\n"
            "– Depending on BACKUP_FULL_PROJECT and BACKUP_FILE_LIST, backups contain the whole project or selected files.\n"
            "– If BACKUP_SEND_TO_TELEGRAM is enabled and size ≤ BACKUP_MAX_SIZE_MB, backup is sent to a Telegram chat; otherwise it stays on the server and you see file path and size.\n\n"
            "🧹 Logs\n"
            "– Logs are written with size-based rotation and automatic cleanup of old log files.\n"
            "– This prevents unlimited log growth and keeps the log directory under control.\n\n"
            "🚫 Bans\n"
            "– You can ban users by ID and specify a reason.\n"
            "– Banned users cannot create new tickets; all existing history remains available for admins.\n"
            "– The ban list shows all banned users and reasons; you can unban them from the same section.\n\n"
            "🌐 Languages\n"
            "– The bot supports at least Russian and English.\n"
            "– Admin language is taken from the admin profile and can be changed in settings.\n"
            "– Users can change their language in the user menu; all texts and keyboards switch accordingly.\n\n"
            "💬 Feedback\n"
            "– After a ticket is closed, the user can rate support on a 1–5 scale.\n"
            "– After rating, you can ask for a text review or suggestion; cooldown protects from spam.\n"
            "– In the admin panel, feedback items have a \"Thank\" button; after thanking, the button becomes inactive.\n\n"
            "💚 Support\n"
            "– If this bot saves your time and helps organize support, you can optionally support development via donation.\n"
        )

    # Russian by default
    return (
        "❓ Помощь админа\n\n"
        "📥 Входящие\n"
        "– Список всех активных тикетов с короткими превью.\n"
        "– В каждом превью: ID тикета, пользователь, статус и чей сейчас ход (👤 пользователь / 🛠 поддержка).\n"
        "– Тикеты, где ход за поддержкой (последним отвечал пользователь), показываются выше остальных.\n"
        "– Внутри групп тикеты отсортированы по времени создания: новые выше, старые ниже.\n\n"
        "📄 Карточка тикета\n"
        "– Полный вид тикета: ID, пользователь, статус (Новый / В работе / Закрыт), время создания и история переписки.\n"
        "– Индикатор хода показывает, от кого ждём ответ; если ход за поддержкой, тикет считается более приоритетным во входящих.\n\n"
        "▶️ Взять в работу\n"
        "– Доступно только для тикетов со статусом «Новый».\n"
        "– Переводит тикет в статус «В работе» и показывает, что вы начали заниматься этим тикетом.\n"
        "– Используйте, чтобы другим админам было видно, что тикет уже в работе.\n\n"
        "💬 Ответ пользователю\n"
        "– Отправляет ваш ответ пользователю с указанием ID тикета, чтобы сохранялся контекст.\n"
        "– После ответа ход переходит к пользователю и запускается таймер авто‑закрытия.\n"
        "– Вы можете отправить несколько ответов; тикет останется открытым, пока вы не закроете его или не сработает авто‑закрытие.\n\n"
        "🔒 Закрыть тикет\n"
        "– Закрывает тикет вручную (статус «Закрыт»).\n"
        "– Используйте, когда вопрос решён или тикет больше не актуален.\n"
        "– Пользователь получает уведомление о закрытии и, если включены оценки, приглашение оценить поддержку.\n\n"
        "⏰ Авто‑закрытие\n"
        "– Срабатывает только если последним отвечала поддержка, а пользователь молчит более X часов.\n"
        "– X задаётся в переменной окружения AUTO_CLOSE_AFTER_HOURS.\n"
        "– При выполнении условия тикет автоматически закрывается со статусом «Закрыт».\n"
        "– Админ и пользователь получают уведомления о закрытии из‑за отсутствия ответа, у пользователя есть кнопка «Задать вопрос» для нового тикета.\n\n"
        "📊 Статистика\n"
        "– Показывает: всего пользователей, всего тикетов, активные и закрытые тикеты.\n"
        "– Отдельно отображаются тикеты в ожидании авто‑закрытия (ход за пользователем, таймер уже тикает).\n"
        "– Есть блок с оценками: сколько тикетов оценено и средняя оценка, а также краткая динамика за последние дни.\n\n"
        "💾 Бэкапы\n"
        "– Автоматические бэкапы создаются планировщиком по расписанию.\n"
        "– Ручной бэкап можно запустить из настроек админа.\n"
        "– В зависимости от BACKUP_FULL_PROJECT и BACKUP_FILE_LIST бэкап содержит весь проект или только выбранные файлы.\n"
        "– Если включена отправка в Telegram и размер ≤ BACKUP_MAX_SIZE_MB, бэкап отправляется в чат; если больше — остаётся на сервере, путь и размер выводятся в сообщении.\n\n"
        "🧹 Логи\n"
        "– Логи пишутся с ротацией по размеру и автоматической очисткой старых файлов.\n"
        "– Это защищает от бесконтрольного роста логов и засорения диска.\n\n"
        "🚫 Блокировки\n"
        "– Можно забанить пользователя по ID и указать причину.\n"
        "– Забанированный пользователь не может создавать новые тикеты; история переписки сохраняется для админа.\n"
        "– В списке банов показываются все заблокированные и причины; там же можно снять блокировку.\n\n"
        "🌐 Языки\n"
        "– Бот поддерживает как минимум русский и английский.\n"
        "– Язык админа берётся из профиля и настраивается в разделе настроек.\n"
        "– Пользователь может сменить язык в своём меню; все тексты и кнопки переключаются на выбранный язык.\n\n"
        "💬 Обратная связь\n"
        "– После закрытия тикета пользователь может оценить работу поддержки по шкале 1–5.\n"
        "– После оценки можно запросить текстовый отзыв или предложение; кулдауны защищают от спама.\n"
        "– В админке отзывы и предложения отображаются с кнопкой «Поблагодарить»; после нажатия кнопка становится неактивной.\n\n"
        "💚 Поддержка проекта\n"
        "– Если бот экономит ваше время и помогает организовать поддержку, можно при желании поддержать разработку донатом.\n"
    )
